services:
  frontend:
    build:
      context: ./react-app
    ports:
      - "3000"
    expose:
      - "3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./node-api
    ports:
      - "5000"
    expose:
      - "5000"

  reverse-proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
